#服务启动端口
server:
  port:  8080

#数据库配置
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.99.100:3306/spring-boot-demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    host: 192.168.99.100
    #redis密码，没有密码的可以用～表示
    password: ~
    port: 6379
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000
mybatis:
  type-aliases-package: bwjava.dao
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml

# 日志输出
logging:
  file: D:/boot.log
  level:
    com.ibatis:DEBUG
    root:DEBUG

task:
  cron:0 0/5 * * * ?
       
    
